[WIP]Adds feature file
CraftAcademy/rails_messaging_june17 pull request #18
Opened 2017-07-26 12:10 UTC by caressahh

Fixes #<replate-me-with-issue-number>

### 

- change 1
- change 2
.
.
- change n

### What did you learn working on this PR?

_list things your learned while working on this_

### Screenshots

_add screenshots here if any visual changes were made to the project_

2017-07-26 12:16 UTC, diraulo commented on features/support/compose_message.feature
> +    Given: I click on the "inbox"
You don't need the `:` after the keywords

2017-07-27 05:24 UTC, j0sv commented
Fixes #6

2017-07-27 05:25 UTC, j0sv commented
Fixes 6

2017-07-27 08:04 UTC, diraulo requested changes
Good that you got this all working

We're still missing a sad path scenario. What happens when the user doesn't fill in all the required field? 

And I also left a few refactoring notes for you.

2017-07-27 08:04 UTC, diraulo commented on Gemfile
> +  gem "capybara"
Use single quotes as the other gems... And also any particular reason why we're explicitly including capybara? 🤔 

I think (and I could be wrong) the `cucumber` gem should include this already

2017-07-27 08:04 UTC, diraulo commented on features/compose_message.feature
> +    Given the following user exist
well if we're creating more than 1 user then we should say `following users exist:`

2017-07-27 08:04 UTC, diraulo commented on features/step_definitions/step_definetions.rb
> +  visit '/'
Make use of the route helper instead. (`root_path` instead of `'/'`)

2017-07-27 08:04 UTC, diraulo commented on features/step_definitions/step_definetions.rb
> +Given(/^I click on the "([^"]*)"$/) do |arg1|
Rename `arg1` to a more meaningful variable name that fits this context

2017-07-27 08:04 UTC, diraulo commented on features/step_definitions/step_definetions.rb
> +Given(/^I click on the "([^"]*)" button$/) do |button_name|
You could refactor this step to work for both links and buttons

So if we have the following 2 steps

```gherkin
Given I click on the "login" link
Given I click on the "login" button
```

we could have a single step definition to match them

```ruby
Given(/^I click on the "([^"]*)" (?:link|button)$/) do |link_or_button_name|
  click_link_or_button link_or_button_name
end
```

2017-07-27 12:04 UTC, diraulo commented
@caressahh @satorinic I need you to do the following to update this PR

1. fetch changes from upstream `git fetch upstream`
2. merge `upstream/master` onto your feature branch `git merge upstream/master`
3. fix any merge conflicts from previous command
4. run `bundle install`
5. commit
6. push to origin

2017-07-27 12:34 UTC, diraulo approved these changes
LGTM 👍

2017-07-27 12:35 UTC, merged

2017-07-27 12:37 UTC, diraulo commented
Fixes #22