User signup acceptance test
CraftAcademy/rails_messaging_june17 pull request #19
Opened 2017-07-26 16:43 UTC by j0sv

Fixes #2 User Signup/registration

### Changes proposed by this PR

- Added User Signup/registration test passed 
- Added User Signup/registration test invalid password and password confirmation not matching passed 
- Added User Signup/registration test missing with missing name passed 

### What did you learn working on this PR?

_list things your learned while working on this_
How to write feature to be able to recycle them in the step definitions.

2017-07-26 19:00 UTC, tochman requested changes

2017-07-26 19:00 UTC, tochman commented on features/step_definitions/basic_step.rb
> +    User.create(user)
Factory Girl is added to Gemfile. Please use it.

2017-07-27 03:37 UTC, j0sv commented on features/step_definitions/basic_step.rb
> +    User.create(user)
Step definition is removed. New step definition is added to branch for login test.

2017-07-27 07:05 UTC, tochman approved these changes

2017-07-27 07:53 UTC, diraulo requested changes
Just minor cleanup on the feature file

2017-07-27 07:53 UTC, diraulo commented on features/user_signup.feature
>    I need to register an accoun
`account`

2017-07-27 07:53 UTC, diraulo commented on features/user_signup.feature
> +
remove line 17 and 18

2017-07-27 07:53 UTC, diraulo commented on features/user_signup.feature
> +#Sad path
remove this..

2017-07-27 09:16 UTC, diraulo approved these changes
LGTM 👍

2017-07-27 09:17 UTC, merged

2017-07-27 12:36 UTC, diraulo commented
Fixed #2

2017-07-27 12:36 UTC, diraulo commented
Fixes #2